# Generated by Django 4.2.29 on 2026-03-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_assignment_skilltag_supportticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfilterpreset',
            name='has_phone',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
