# Generated by Django 4.2.29 on 2026-03-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('alumni', 'Alumni')], default='active', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
